### ISSUE TITLE
[EASY QUESTION] Hollow Cylinder as Surface

### ISSUE THREAD

**Issue by mia0120** [meshpro/pygmsh#512]
Hello, How can I create a hollow cylinder as surface? It hoas no thickness, ONLY Surface??
Thanks in advance..

**Comment by mia0120** [comment]
![t725](https://user-images.githubusercontent.com/98092736/150342987-91acb335-7e1f-487f-9fcb-922636f61a48.png)

**Comment by nschloe** [comment]
Take a look at meshzoo: https://github.com/nschloe/meshzoo#tube.
